// <auto-generated />
namespace chuipala_ws.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Init3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init3));
        
        string IMigrationMetadata.Id
        {
            get { return "201606131921502_Init3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
